# Generated by Django 3.0.5 on 2020-05-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MondayAppreciationClub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='created',
        ),
        migrations.AddField(
            model_name='stock',
            name='company_name',
            field=models.TextField(default='_'),
        ),
        migrations.AddField(
            model_name='stock',
            name='ticker',
            field=models.CharField(default='_', max_length=5),
        ),
    ]
